---

version: '3'

env:
  CONFIG_FILE: ./conf.py
  FLASK_APP: penny

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  db:migrate:
    cmds:
      - poetry run flask db migrate
  db:upgrade:
    envs:
      - PENNY_SKIP_IMPORT_ALL_TYPES: 1
    cmds:
      - poetry run flask db upgrade
  build:
    cmds:
      - poetry install --no-dev
  build:dev:
    cmds:
      - poetry install
  run:queue:
    env:
      CONFIG_FILE: ./conf.py
    cmds:
      - poetry run rqworker --url redis://localhost:6379/0 --verbose --path=.
  run:www:
    env:
      FLASK_DEBUG: 1
      FLASK_APP: penny
      CONFIG_FILE: ./conf.py
      PENNY_IMPORT_ALL_TYPES: 1
    vars:
      FLASK_HOST: 127.0.0.1
      FLASK_PORT: 5000
    cmds:
      - mkdir -p files/transactions files/uploads
      - poetry run flask run --host={{ .FLASK_HOST }} --port={{ .FLASK_PORT }}
  docker:build:
    vars:
      VERSION:
        sh: poetry version --short
    cmds:
      - docker build . -t rene00/penny:{{ .VERSION }}
  docker:run:
    vars:
      VERSION:
        sh: poetry version --short
      HOST_PORT: 5000
    cmds:
      - |
        docker run -it --restart always \
          --publish {{ .HOST_PORT }}:5000 \
          -e CONFIG_FILE=/app/penny/conf.py \
          --mount source=penny,target=/penny \
          --name penny rene00/penny:{{ .VERSION }}
  test:
    cmds:
      - |
        poetry run pycodestyle \
          --ignore=E121,E123,E126,E226,E24,E704,W503,E711,E712,E501 penny
      - poetry run pytest .
  seed:init:
    env:
      FLASK_DEBUG: 1
      FLASK_APP: penny
      CONFIG_FILE: ./conf.py
    cmds:
      - poetry run flask seed init
  task:tag_match:
    env:
      FLASK_DEBUG: 1
      FLASK_APP: penny
      CONFIG_FILE: ./conf.py
    cmds:
      - poetry run flask task tag_match
