---

version: '3'

env:
  CONFIG_FILE: ./conf.py
  FLASK_APP: penny

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  db:upgrade:
    envs:
      - PENNY_SKIP_IMPORT_ALL_TYPES: 1
    cmds:
      - poetry run flask db upgrade
  build:
    cmds:
      - poetry install --no-dev
  run:queue:
    env:
      CONFIG_FILE: ./conf.py
    cmds:
      - poetry run rqworker --url redis://localhost:6379/0 --verbose --path=.
  run:www:
    env:
      FLASK_DEBUG: 1
      CONFIG_FILE: ./conf.py
      FLASK_APP: penny
    vars:
      FLASK_HOST: 127.0.0.1
      FLASK_PORT: 5000
    cmds:
      - mkdir -p files/transactions files/uploads
      - poetry run flask run --host={{ .FLASK_HOST }} --port={{ .FLASK_PORT }}
  docker:build:
    vars:
      VERSION:
        sh: poetry version --short
    cmds:
      - docker build . -t rene00/penny:{{ .VERSION }}
  docker:run:
    vars:
      VERSION:
        sh: poetry version --short
      HOST_PORT: 5000
    cmds:
      - docker run -dit --restart always \
        --publish {{ .HOST_PORT }}:5000 \
        -e CONFIG_FILE=/app/penny/conf.py \
        --mount source=penny,target=/penny \
        --name penny rene00/penny:{{ .VERSION }}
