"""empty message

Revision ID: 474a7b3c5c13
Revises: 82ff85d6d7e5
Create Date: 2016-03-25 04:56:45.159946

"""

# revision identifiers, used by Alembic.
revision = '474a7b3c5c13'
down_revision = '82ff85d6d7e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
