"""empty message

Revision ID: 4ef27bbd49ce
Revises: e6f93b17d62e
Create Date: 2022-04-17 17:09:52.206017

"""

# revision identifiers, used by Alembic.
revision = '4ef27bbd49ce'
down_revision = 'e6f93b17d62e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permissions', sa.UnicodeText(), nullable=True))
    op.add_column('role', sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('user', sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('user', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('current_login_ip', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('tf_phone_number', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('tf_primary_method', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('tf_totp_secret', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('user', sa.Column('us_phone_number', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('us_totp_secrets', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=True))
    with op.batch_alter_table("user") as batch_op:
        batch_op.create_unique_constraint("user_username_unique", ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'us_totp_secrets')
    op.drop_column('user', 'us_phone_number')
    op.drop_column('user', 'update_datetime')
    op.drop_column('user', 'tf_totp_secret')
    op.drop_column('user', 'tf_primary_method')
    op.drop_column('user', 'tf_phone_number')
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'current_login_ip')
    op.drop_column('user', 'current_login_at')
    op.drop_column('user', 'create_datetime')
    op.drop_column('role', 'update_datetime')
    op.drop_column('role', 'permissions')
    # ### end Alembic commands ###
