"""empty message

Revision ID: 82ff85d6d7e5
Revises: 56bac2207b80
Create Date: 2016-03-25 04:43:15.333807

"""

# revision identifiers, used by Alembic.
revision = '82ff85d6d7e5'
down_revision = '56bac2207b80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed_at')
    ### end Alembic commands ###
