"""empty message

Revision ID: 9d0219be4f0e
Revises: f27378b083d1
Create Date: 2023-08-27 09:38:24.131107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0219be4f0e'
down_revision = 'f27378b083d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tx_meta_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tx_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.Integer(), nullable=False),
    sa.Column('tx_meta_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tx_id'], ['tx.id'], ),
    sa.ForeignKeyConstraint(['tx_meta_type_id'], ['tx_meta_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_id', 'tx_meta_type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tx_meta')
    op.drop_table('tx_meta_type')
    # ### end Alembic commands ###
