"""empty message

Revision ID: f490e985f5c9
Revises: 474a7b3c5c13
Create Date: 2016-03-26 07:01:27.494121

"""

# revision identifiers, used by Alembic.
revision = 'f490e985f5c9'
down_revision = '474a7b3c5c13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('alpha_enabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'alpha_enabled')
    ### end Alembic commands ###
