name: container

on:
  push:
    tags:
      - '*'
    branches:
      - 'master'
      - 'fix-container-registry'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Install task
        run: |
          mkdir -p ~/.local/bin
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      -
        name: Build and push
        run: |
          ls -la
          find .
          task docker:build docker:push
