name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install system packages
        run: sudo apt-get install -y python3 python3-dev python3-pip python3-setuptools libpython3-dev tox gcc libffi-dev libxml2-dev libxslt1-dev libssl-dev locales
      - name: Setup locale
        run:  echo 'en_AU.UTF-8 UTF-8' | sudo tee /etc/locale.gen && sudo /usr/sbin/locale-gen 
      - name: Run tox
        run: tox
