name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: sudo apt-get install -y tox gcc libffi-dev libxml2-dev libxslt1-dev libssl-dev locales

      - name: Setup locale
        run:  echo 'en_AU.UTF-8 UTF-8' | sudo tee /etc/locale.gen && sudo /usr/sbin/locale-gen 

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 - --version 1.1.13

      - name: Install dependencies
        run: poetry install

      - name: Run tox
        run: poetry run tox
