name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y tox gcc libffi-dev libxml2-dev libxslt1-dev libssl-dev locales

      - name: Setup locale
        run:  echo 'en_AU.UTF-8 UTF-8' | sudo tee /etc/locale.gen && sudo /usr/sbin/locale-gen 

      - name: Run tox
        run: tox
