---
name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.7.3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9.17

      - name: Install dependencies
        run: |
          sudo apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev \
            libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev \
            libffi-dev liblzma-dev gcc libxml2-dev libxslt1-dev locales

      - name: Install pipx
        run: pip install pipx

      - name: Install poetry
        run: pipx install poetry==1.5.1

      - name: Install dependencies
        run: poetry install

      - name: Setup locale
        run: echo 'en_AU.UTF-8 UTF-8' | sudo tee /etc/locale.gen && sudo /usr/sbin/locale-gen

      - name: Run tests
        run: task test
